<html>
    <head>
	     
       <link rel="stylesheet" type="text/css" href="style3.css">
    
    </head>

<body>

<div class="container">  
  <form id="contact" action="eliminarEquipamentoCod.php" method="post">
    
    <center><h3>Eliminar Equipamento</h3></center><br>
    
    <fieldset>
        <input placeholder="ID do equipamento que pretende eliminar" type="text"  name="id_equipamento">
    </fieldset>
    
    <fieldset>
        <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Eliminar</button>
    </fieldset>
   
  </form>
</div>

</body>
</html>