<html>
  <head>
	
     <link rel="stylesheet" type="text/css" href="style3.css">
  
  </head>

<body>

<div class="container">  
<form id="contact" action="eliminarclientecod.php" method="post">
    
    <center><h3>Eliminar Cliente</h3></center><br>
    
    <fieldset>
        <input placeholder="ID do cliente que pretende eliminar" type="text"  name="id_cliente">
    </fieldset>
    
    <fieldset>
        <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Eliminar</button>
    </fieldset>
   
</form>
</div>



</body>
</html>

